// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xchcwvnyjpvwkbuuxopu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaGN3dm55anB2d2tidXV4b3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDkyOTEsImV4cCI6MjA2ODkyNTI5MX0.c8VvHQ_Y5XsbM0IMKNXe8mGafHkJE_N5-kSRnU94_-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});